/******************************************************************************
Finite State Machine
Project: PMQ
Description: Portenta WiFi MQTT

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.2.1
Generation date: 2020-09-01 12:25:43 +0200
Generated from: fsm.dot
The finite state machine has:
  0 states
  0 transition functions
******************************************************************************/

